name: Wakatime Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'
  
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          COMMIT_MESSAGE: "Updating profile stats"
          SHOW_EDITORS: false
          SHOW_LINES_OF_CODE: false
          SHOW_LOC_CHART: false
          SHOW_OS: false
          SHOW_PROFILE_VIEWS: false
          SHOW_PROJECTS: false
          SHOW_SHORT_INFO: false
          SHOW_UPDATED_DATE: false
